image: docker

stages:
  - build
  
before_script:
  - service_name=$(echo $CI_PROJECT_PATH | sed 's;/;.;g')
  - export VERSION=$CI_COMMIT_TAG
  - |
    if [[ -z "$VERSION" ]]; then
        export VERSION=$CI_COMMIT_REF_NAME
    fi

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - export IMAGE=binhfile/facebook-mqtt-bridge:$VERSION
    - echo $CI_DEPLOY_SECRET | docker login -u $CI_DEPLOY_USER --password-stdin
    - docker build -t $IMAGE -f Dockerfile .
    - docker push $IMAGE
  only:
    - master
    - develop
    - tags
